### ISSUE TITLE
Code don't work and I'm too stupid to fix

### ISSUE THREAD

**Issue by XxStarDragonxX** [Joursoir/gpgme-example-code#1]
I just installed gpgme to try it for school, I donwloaded and compiled your code but when I run it gives me this
`encrypt.c:31: GPGME: End of file`
Maybe my version is wrong but I've just downloaded and don't know how to make it work
```
 gpgme-config --version ; gpgme-config --api-version
1.18.0
1
```
this code I think is the problem
```
    err = gpgme_get_key(ctx, gpg_key, &key[0], 0);
    exit_if_err(err);

```
This is a stupid question and I could figure it out myself but please if you instantly know what the problem is tell me

**Comment by Joursoir** [comment]
Hello XxStarDragonxX,

Please have a look at the source code of `encrypt.c`, line 8:
``` c
const char gpg_key[] = "your-public-key";
```

You should use your public key from GPG. It can be obtained by using `gpg --list-key` command, e.g:

```
[triste@pc gpgme-example-code]$ gpg --list-key
/home/triste/.gnupg/pubring.kbx
-------------------------------
pub   rsa3072 2020-11-14 [SC]
      E40AD7F10ED0394BFCCA4DCBC4447D6434CB80C6
uid           [ unknown] example <example@gmail.com>
```

In this case, if I use `E40AD7F10ED0394BFCCA4DCBC4447D6434CB80C6` then everything will work.

**Comment by XxStarDragonxX** [comment]
> Hello XxStarDragonxX,
> 
> Please have a look at the source code of `encrypt.c`, line 8:
> ``` c
> const char gpg_key[] = "your-public-key";
> ```
> 
> You should use your public key from GPG. It can be obtained by using `gpg --list-key` command, e.g:
> 
> ```
> [triste@pc gpgme-example-code]$ gpg --list-key
> /home/triste/.gnupg/pubring.kbx
> -------------------------------
> pub   rsa3072 2020-11-14 [SC]
>       E40AD7F10ED0394BFCCA4DCBC4447D6434CB80C6
> uid           [ unknown] example <example@gmail.com>
> ```
> 
> In this case, if I use `E40AD7F10ED0394BFCCA4DCBC4447D6434CB80C6` then everything will work.

Ok thanks, in the end i found a way to create my own program

**Comment by Joursoir** [comment]
Good! I'm happy that you figured out what's wrong.
